# fly.toml app configuration file generated for tsharkey-rss-wispy-voice-5209 on 2025-05-10T09:23:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tsharkey-rss-wispy-voice-5209'
primary_region = 'bos'
kill_signal = 'SIGINT'
kill_timeout = '2m0s'

[build]
  image = 'freshrss/freshrss:latest'

[env]
  CRON_MIN = '*/20'

[[mounts]]
  source = 'freshrss_data'
  destination = '/var/www/FreshRSS/data'
  initial_size = '1gb'

[[services]]
  protocol = 'tcp'
  internal_port = 80
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
